services:
  - type: web
    name: mini-erp-crm-backend
    env: node
    region: singapore
    buildCommand: npm install && npx prisma generate && npm run build && npm run seed
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_EXPIRES_IN
        value: 7d
